ref_genome: "/path_to/my_ref_genome.fasta"
pop_index: "/path_to//id_pop.tsv"
reads_dir: "/path_to/my_reads/
threads: 30
gstacks:
  input_dir: "00-reads/"
  output_dir: "01-gstacks/"
  logs: "logs/01-gstacks.log"
  min_map_quality: 30
fasta2bed:
  dir_script: "scripts/"
  dir_stacks: "01-gstacks/"
  logs: "logs/01-fasta2bed.log"
bcftools_call:
  output_dir: "02-bcftools_call/"
  logs: "logs/02-bcftools_call_"
vcftools_filter:
  output_dir: "03-vcftools_filter/"
  logs: "logs/03-vcftools_filter_"
  minDP: 15
bcftools_sort:
  logs: "logs/03-bcftools_sort_"
bcftools_merge:
  output_dir: "04-bcftools_merge/"
  logs: "logs/04-bcftools_"
python_filter:
  output_dir: "05-python_filter/"
  logs: "logs/05-python_"
  mac: 1   # Set to include only sites with Minor Allele Count greater than or equal to mac
piawka:
  script_dir: scripts/piawka/
  output_dir: "06-genomic_diversity/"
  log_pi:  "logs/06-piawka_pi_dxy_fst.log"
  log_het: "logs/06-piawka_het.log"
piawka_agg:
  output_dir: "06-genomic_diversity/"
  logs: "logs/07-piawka_agg_"
